<h1 class="mt-4"><?= htmlspecialchars($url['name']) ?></h1>
<table data-test="url" class="table mt-3">
    <tbody>
        <tr>
            <th>ID</th>
            <td><?= $url['id'] ?></td>
        </tr>
        <tr>
            <th>Имя</th>
            <td><?= htmlspecialchars($url['name']) ?></td>
        </tr>
        <tr>
            <th>Дата создания</th>
            <td><?= $url['created_at'] ?></td>
        </tr>
    </tbody>
</table>

<form method="post" action="/urls/<?= $url['id'] ?>/checks">
    <input type="submit" value="Запустить проверку" class="btn btn-primary mt-3">
</form>

<table data-test="checks" class="table mt-4">
    <thead>
        <tr>
            <th>ID</th>
            <th>Код ответа</th>
            <th>h1</th>
            <th>title</th>
            <th>description</th>
            <th>Дата создания</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($checks as $check): ?>
        <tr>
            <td><?= $check['id'] ?></td>
            <td><?= $check['status_code'] ?></td>
            <td><?= htmlspecialchars(mb_strimwidth($check['h1'] ?? '', 0, 200, '...')) ?></td>
            <td><?= htmlspecialchars(mb_strimwidth($check['title'] ?? '', 0, 200, '...')) ?></td>
            <td><?= htmlspecialchars(mb_strimwidth($check['description'] ?? '', 0, 200, '...')) ?></td>
            <td><?= $check['created_at'] ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
