<div class="mt-4">
    <h1 class="display-4">Анализатор страниц</h1>
    <p class="lead">Проверяйте сайты на SEO-пригодность</p>
    <hr class="my-4">
    <form action="/urls" method="post">
        <div class="input-group">
            <input
                type="text"
                name="url"
                class="form-control form-control-lg <?= !empty($errors['url']) ? 'is-invalid' : '' ?>"
                placeholder="https://www.example.com"
                value="<?= htmlspecialchars($url ?? '') ?>"
            >
            <button class="btn btn-primary btn-lg" type="submit" value="Проверить">Проверить</button>
        </div>
        <?php if (!empty($errors['url'])): ?>
            <div class="invalid-feedback d-block">
                <?= htmlspecialchars($errors['url'][0]) ?>
            </div>
        <?php endif ?>
    </form>
</div>
