<div class="jumbotron mt-4">
    <h1 class="display-4">Анализатор страниц</h1>
    <p class="lead">Проверяйте сайты на SEO-пригодность</p>
    <hr class="my-4">
    <form action="/urls" method="post">
        <div class="input-group">
            <input type="text" name="url" class="form-control form-control-lg" placeholder="https://example.com">
            <button class="btn btn-primary btn-lg" type="submit">Проверить</button>
        </div>
    </form>
</div>
